un = INPUT("What is your name?")
print ("Hi, " + un + "!")
uos = INPUT("What is your favorite OS to code on?")
up = INPUT("What is your favorite program to code with?")
print ("Cool! I like using " + up + " on " + uos + "too!")
x = INPUT("Press enter to quit.")